# Generated by Django 4.0.1 on 2022-02-14 16:38

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateField(auto_now=True)),
                ('eliminated_at', models.DateField(auto_now=True)),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('email', models.EmailField(max_length=200)),
                ('descripcion', models.TextField()),
                ('web', models.URLField(blank=True, null=True)),
                ('Facebook', models.URLField(blank=True, null=True)),
                ('Twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('photo', models.ImageField(upload_to='autores/')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateField(auto_now=True)),
                ('eliminated_at', models.DateField(auto_now=True)),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=150)),
                ('imagen_referencial', models.ImageField(upload_to='categorias/')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateField(auto_now=True)),
                ('eliminated_at', models.DateField(auto_now=True)),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=150)),
                ('imagen_referencial', models.ImageField(upload_to='subcategorias/')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myblog.categoria')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateField(auto_now=True)),
                ('eliminated_at', models.DateField(auto_now=True)),
                ('titulo', models.CharField(max_length=50, unique=True)),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=150)),
                ('ruta', models.CharField(max_length=150)),
                ('imagen_referencial', models.ImageField(upload_to='articulos/')),
                ('publicado', models.BooleanField(default=False)),
                ('fecha_publicacion', models.DateField()),
                ('contenido', ckeditor.fields.RichTextField()),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myblog.author')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myblog.categoria')),
                ('subcategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myblog.subcategoria')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
