# Generated by Django 4.0.1 on 2022-02-14 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoria',
            table=None,
        ),
    ]
