# Generated by Django 4.0.1 on 2022-02-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_alter_categoria_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulos',
            options={'verbose_name': 'Artículo', 'verbose_name_plural': 'Artículos'},
        ),
       
    ]
