# Generated by Django 4.0.1 on 2022-02-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_alter_articulos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagen_referencial',
            field=models.ImageField(upload_to='aplicaciones/myblog/media/img/categorias/'),
        ),
    ]
