# Generated by Django 4.0.1 on 2022-02-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_alter_categoria_imagen_referencial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='imagen_referencial',
            field=models.ImageField(upload_to='aplicaciones/myblog/articulos/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(upload_to='aplicaciones/myblog/autores/'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='imagen_referencial',
            field=models.ImageField(upload_to='aplicaciones/myblog/subcategorias/'),
        ),
    ]
