# Generated by Django 4.0.1 on 2022-02-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0008_alter_articulos_imagen_referencial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='imagen_referencial',
            field=models.ImageField(upload_to='aplicaciones/myblog/media/img/articulos/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(upload_to='aplicaciones/myblog/media/img/autores/'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='imagen_referencial',
            field=models.ImageField(upload_to='aplicaciones/myblog/media/img/categorias/'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='imagen_referencial',
            field=models.ImageField(upload_to='aplicaciones/myblog/media/img/subcategorias/'),
        ),
    ]
